export const SET_CHARACTER = 'SET_CHARACTER';
export const CALL_SET_CHARACTER = 'CALL_SET_CHARACTER';
export const CALL_LISTEN_CHARACTER = 'CALL_LISTEN_CHARACTER';
export const CALL_LISTEN_OTHER_CHARACTER = 'CALL_LISTEN_OTHER_CHARACTER';
export const CALL_SELECT_OTHER_CHARACTER = 'CALL_SELECT_OTHER_CHARACTER';
export const CALL_CREATE_CHARACTER = 'CALL_CREATE_CHARACTER';
export const UPDATE_CHARACTER = 'UPDATE_CHARACTER';
export const CANCEL_LISTEN_CHARACTER = 'CANCEL_LISTEN_CHARACTER';
