export const SET_ITEM_LIST = "SET_ITEM_LIST";
export const CALL_GET_ITEM_LIST = "CALL_GET_ITEM_LIST";

export const SET_ARTEFACT_LIST = "SET_ARTEFACT_LIST";
export const CALL_LISTEN_ARTEFACT_LIST = "CALL_LISTEN_ARTEFACT_LIST";
