export const SET_TILES_TYPES = "SET_TILES_TYPES";
export const CALL_SET_TILES_TYPES = "CALL_SET_TILES_TYPES";
export const CALL_LISTEN_MAP_TILES = "CALL_LISTEN_MAP_TILES";
export const SET_MAP_TILES = "SET_MAP_TILES";
