export const SET_CHARACTER = "SET_CHARACTER";
export const SET_CHARACTER_ID = "SET_CHARACTER_ID";
export const SET_CHARACTER_CREATION= "SET_CHARACTER_CREATION";
export const CALL_SET_CHARACTER = "CALL_SET_CHARACTER";
export const CALL_LISTEN_CHARACTER = "CALL_LISTEN_CHARACTER";
export const CALL_LISTEN_OTHER_CHARACTER = "CALL_LISTEN_OTHER_CHARACTER";
