export const SET_MERCHANT_LIST = "SET_MERCHANT_LIST";
export const CALL_GET_MERCHANT_LIST = "CALL_GET_MERCHANT_LIST";
export const CALL_LISTEN_MERCHANT_LIST = "CALL_LISTEN_MERCHANT_LIST";
export const SET_CURRENT_MERCHANT = "SET_CURRENT_MERCHANT";
