export const SET_CURRENT_EVENT = "SET_CURRENT_EVENT";
export const CALL_LISTEN_CURRENT_EVENT = "CALL_LISTEN_CURRENT_EVENT";
export const SET_EVENTS_HISTORY = "SET_EVENTS_HISTORY";
export const CALL_LISTEN_EVENTS_HISTORY = "CALL_LISTEN_EVENTS_HISTORY";
