export const PRINT_ERROR = "PRINT_ERROR";
export const TOGGLE_PLAYER_VIEW = "TOGGLE_PLAYER_VIEW";
export const TOGGLE_PLAYER_MASTERING = "TOGGLE_PLAYER_MASTERING";
export const UPDATE_CURRENT_STORY = "UPDATE_CURRENT_STORY";
export const SET_GAME_MASTER = "SET_GAME_MASTER";
