export const TOGGLE_MUSIC = "TOGGLE_MUSIC";
export const CALL_RESET_SOUNDS = "CALL_RESET_SOUNDS";
export const RESET_SOUNDS = "RESET_SOUNDS";
export const TOGGLE_MUSIC_FIRST = "TOGGLE_MUSIC_FIRST";

export const STOP_NOISE = "STOP_NOISE";
export const CALL_STOP_NOISE = "CALL_STOP_NOISE";
export const STOP_SONG = "STOP_SONG";
export const CALL_STOP_SONG = "CALL_STOP_SONG";

export const LOAD_SONG = "LOAD_SONG";
export const CALL_LOAD_SONG = "CALL_LOAD_SONG";
export const LOAD_MUSIC = "LOAD_MUSIC";
export const CALL_LOAD_MUSIC = "CALL_LOAD_MUSIC";
export const LOAD_NOISE = "LOAD_NOISE";
export const CALL_LOAD_NOISE = "CALL_LOAD_NOISE";

export const CALL_LISTEN_MUSIC = "CALL_LISTEN_MUSIC";
export const CALL_LISTEN_NOISE = "CALL_LISTEN_NOISE";
export const CALL_LISTEN_SONG = "CALL_LISTEN_SONG";

export const UPDATE_ALL_MUSIC = "UPDATE_ALL_MUSIC";
